In [1]:
import numpy as np
Marks=np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])
print(Marks)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [2]:
print(Marks.size)
print(Marks.shape)
print(Marks.dtype)

print(Marks[1])
print(Marks[:, 2])
np.sum(Marks+5)

15
(5, 3)
int32
[45 60 55]
[90 55 95 35 75]


1078

In [8]:
# for  row in Marks:
#     for i in row:
#         if i>= 50:
#             print("Pass")
#         else:
#             print("Fail")
result  = np.where(Marks>50,"Pass","Fail")
print(result)

[['Pass' 'Pass' 'Pass']
 ['Fail' 'Pass' 'Pass']
 ['Pass' 'Pass' 'Pass']
 ['Fail' 'Fail' 'Fail']
 ['Pass' 'Pass' 'Pass']]


In [12]:
average = np.mean(Marks,axis=0)
result = np.where(average>=85,"GRADE A ",np.where(average>=70,"GRADE B",np.where(average>=50,"GRADE c","GRADE D")))
print(result)

['GRADE c' 'GRADE c' 'GRADE B']


In [31]:
copyarr = Marks.copy()
print(copyarr)
print(" ")
Marks[0,0]=0
print(Marks)

[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
 
[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
