In [48]:
import numpy as np
Marks=np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])
print(Marks)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [49]:
print(Marks.size)
print(Marks.shape)
print(Marks.dtype)

print(Marks[1])
print(Marks[:, 2])
np.sum(Marks+5)

15
(5, 3)
int64
[45 60 55]
[90 55 95 35 75]


np.int64(1078)

In [50]:
# for  row in Marks:
#     for i in row:
#         if i>= 50:
#             print("Pass")
#         else:
#             print("Fail")
result  = np.where(Marks>50,"Pass","Fail")
print(result)

[['Pass' 'Pass' 'Pass']
 ['Fail' 'Pass' 'Pass']
 ['Pass' 'Pass' 'Pass']
 ['Fail' 'Fail' 'Fail']
 ['Pass' 'Pass' 'Pass']]


In [51]:
average = np.mean(Marks,axis=0)
result = np.where(average>=85,"GRADE A ",np.where(average>=70,"GRADE B",np.where(average>=50,"GRADE c","GRADE D")))
print(result)

['GRADE c' 'GRADE c' 'GRADE B']


In [52]:
copyarr = Marks.copy()
print(copyarr)
print(" ")
Marks[0,0]=0
print(Marks)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
 
[[ 0 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [53]:
electricity = np.array([np.random.randint(120,650,size=(4,7))])

average = np.mean(electricity,axis=1)
maximum = np.max(electricity,axis=1)
print(average)
print(" ")
print(maximum)


[[365.5  394.5  179.75 356.25 373.   387.25 348.25]]
 
[[604 582 260 480 608 613 519]]


In [54]:
policy = np.where(electricity>550,electricity*0.2+electricity,electricity)
print(electricity)

[[[150 582 172 142 154 194 455]
  [411 254 260 480 545 613 178]
  [604 425 140 347 185 323 241]
  [297 317 147 456 608 419 519]]]


In [55]:
compare = electricity > average
print(compare)

[[[False  True False False False False  True]
  [ True False  True  True  True  True False]
  [ True  True False False False False False]
  [False False False  True  True  True  True]]]


In [56]:
electricity.reshape(1,28)

array([[150, 582, 172, 142, 154, 194, 455, 411, 254, 260, 480, 545, 613,
        178, 604, 425, 140, 347, 185, 323, 241, 297, 317, 147, 456, 608,
        419, 519]], dtype=int32)

In [57]:
reshaped = electricity.reshape(2,14)
print(reshaped)

[[150 582 172 142 154 194 455 411 254 260 480 545 613 178]
 [604 425 140 347 185 323 241 297 317 147 456 608 419 519]]


In [ ]:
ref_backup = electricity   #copy by reference 
safe_backup = electricity.copy()  #copy by value 
electricity[0,0,1]= 56 
print(electricity)
print(" ")
print(ref_backup)
print(" ")
print(safe_backup)

[[[150  56 172 142 154 194 455]
  [411 254 260 480 545 613 178]
  [604 425 140 347 185 323 241]
  [297 317 147 456 608 419 519]]]
 
[[[150  56 172 142 154 194 455]
  [411 254 260 480 545 613 178]
  [604 425 140 347 185 323 241]
  [297 317 147 456 608 419 519]]]
 
[[[150 582 172 142 154 194 455]
  [411 254 260 480 545 613 178]
  [604 425 140 347 185 323 241]
  [297 317 147 456 608 419 519]]]
